package msi

import "fmt"

// msi_patch_transform.go — P10 construction of the two patch transforms.
//
// A patch carries two MST sub-storages applied to the installed product:
//   - product transform "P0": the File changes (re-sequenced into the patch
//     cabinet's media range) plus any minor-upgrade additions and the new
//     ProductVersion. Its summary carries the Product validation flag.
//   - metadata transform "#P0": the patch bookkeeping — the patch Media row
//     (embedded cab, with Source set), the Patch rows, and the PatchPackage row.
//
// Each transform is built by materializing a synthetic target database (base
// plus the relevant changes) and diffing it against the base with the
// schema-additive transform builder (buildPatchTransformStreams), so the
// metadata transform can introduce the Patch/PatchPackage tables the base lacks.
// The synthetic targets are intentionally NOT validated for cross-table foreign
// keys: those resolve only after BOTH transforms apply at install time.

// patchWorkTable is a mutable table (columns + raw value rows) used while
// assembling a patch transform target.
type patchWorkTable struct {
	cols []msiColumn
	rows [][]any
}

// patchWorkDB is a mutable working copy of a database for building a transform
// target. _Tables/_Columns are regenerated by materialize().
type patchWorkDB struct {
	tables       map[string]*patchWorkTable
	fileContents map[string][]byte
}

// workDBFromDatabase clones every user table (fresh columns + copied rows) of db
// into a mutable working database.
func workDBFromDatabase(db msiDatabase) *patchWorkDB {
	w := &patchWorkDB{tables: map[string]*patchWorkTable{}, fileContents: map[string][]byte{}}
	for k, v := range db.FileContents() {
		w.fileContents[k] = v
	}
	for _, name := range db.Tables() {
		if name == msiTablesTableName || name == msiColumnsTableName {
			continue
		}
		tbl, _ := db.GetTable(name)
		cols := tbl.columns()
		var rows [][]any
		for _, r := range tbl.rows() {
			rows = append(rows, padCells(r.values(), len(cols)))
		}
		w.tables[name] = &patchWorkTable{cols: cols, rows: rows}
	}
	return w
}

// ensureTable returns the named working table, creating it from a catalog
// factory's columns when absent.
func (w *patchWorkDB) ensureTable(name string, factory func() msiTable) *patchWorkTable {
	if wt, ok := w.tables[name]; ok {
		return wt
	}
	wt := &patchWorkTable{cols: factory().columns()}
	w.tables[name] = wt
	return wt
}

// upsertFromDB merges inserts and updates (by primary key) from up into the
// working database for every table not in skip. Rows present only in the base
// are kept (patches never remove rows).
func (w *patchWorkDB) upsertFromDB(up msiDatabase, skip map[string]bool) {
	for _, name := range up.Tables() {
		if name == msiTablesTableName || name == msiColumnsTableName || skip[name] {
			continue
		}
		ut, _ := up.GetTable(name)
		cols := ut.columns()
		wt, ok := w.tables[name]
		if !ok {
			wt = &patchWorkTable{cols: cols}
			w.tables[name] = wt
		}
		keyIdx := keyColumnIndexes(cols)
		idx := map[string]int{}
		for i, row := range wt.rows {
			idx[rowKeyString(row, keyIdx)] = i
		}
		for _, r := range ut.rows() {
			vals := padCells(r.values(), len(cols))
			k := rowKeyString(vals, keyIdx)
			if j, ok := idx[k]; ok {
				wt.rows[j] = vals
			} else {
				wt.rows = append(wt.rows, vals)
				idx[k] = len(wt.rows) - 1
			}
		}
	}
}

// materialize builds a read-only msiDatabase from the working tables, with
// _Tables/_Columns regenerated from the final table set. Rows are validated for
// shape only (addRow); cross-table foreign keys are NOT checked.
func (w *patchWorkDB) materialize() (msiDatabase, error) {
	d := &msiDB{tables: make(map[string]msiTable), fileContents: w.fileContents}
	for name, wt := range w.tables {
		tbl := newMSITableBuilder().WithName(name).WithColumns(wt.cols...).Build()
		for _, vals := range wt.rows {
			row := newMSIRowBuilder().WithColumns(wt.cols...).WithValues(vals...).Build()
			if err := tbl.addRow(row); err != nil {
				return nil, fmt.Errorf("patch target: table %s: %w", name, err)
			}
		}
		d.tables[name] = tbl
	}
	if err := d.populateSystemCatalog(); err != nil {
		return nil, fmt.Errorf("patch target: %w", err)
	}
	return d, nil
}

// buildPatchProductTransform builds the product transform ("P0"): File changes
// re-sequenced into the patch cabinet, plus minor-upgrade additions and the new
// ProductVersion, diffed against the base.
func (p *msiPatch) buildPatchProductTransform() ([]msiStream, error) {
	w := workDBFromDatabase(p.baseDB)
	// Bring in additions/metadata changes from the upgraded package, EXCEPT the
	// File and Media tables (handled specially so files come from the patch cab).
	w.upsertFromDB(p.upDB, map[string]bool{msiFileTableName: true, msiMediaTableName: true})

	if err := p.applyFileChangesToWork(w); err != nil {
		return nil, err
	}

	target, err := w.materialize()
	if err != nil {
		return nil, err
	}
	// VALIDATE_PRODUCT binds the patch to the target product: real Windows
	// msiexec needs a transform to validate the ProductCode (against the
	// transform's PID9 lineage) to consider the patch applicable to the
	// installed product — without it, it returns 1642 (ERROR_PATCH_TARGET_NOT_
	// FOUND). The PID16 error flags still suppress benign add/del errors, and
	// Wine accepts PRODUCT (it is in its supported-flags set).
	summary := (&msiTransform{base: p.base, target: p.upgraded, validation: TransformValidateProduct, errorConditions: patchTransformErrorSuppress}).summaryInfo()
	return buildPatchTransformStreams(p.baseDB, target, summary)
}

// applyFileChangesToWork rewrites the working File table: changed files adopt the
// upgraded file's metadata at a patch sequence number; new files are appended
// (PatchAdded) at a patch sequence; unchanged files keep their base rows.
func (p *msiPatch) applyFileChangesToWork(w *patchWorkDB) error {
	ft, ok := w.tables[msiFileTableName]
	if !ok {
		return nil
	}
	upFiles := fileRowsByID(p.upDB)
	changeByID := map[string]patchFileChange{}
	for _, c := range p.changes {
		changeByID[c.fileID] = c
	}

	var rows [][]any
	for _, row := range ft.rows {
		id, _ := row[0].(string)
		if ch, ok := changeByID[id]; ok && !ch.isNew {
			up := upFiles[id]
			nr := padCells(up, len(ft.cols))
			nr[7] = ch.sequence // Sequence -> patch range
			rows = append(rows, nr)
			continue
		}
		rows = append(rows, row)
	}
	for _, ch := range p.changes {
		if !ch.isNew {
			continue
		}
		up := upFiles[ch.fileID]
		nr := padCells(up, len(ft.cols))
		nr[7] = ch.sequence
		nr[6] = orInt16(nr[6], msidbFileAttributesPatchAdded) // Attributes
		rows = append(rows, nr)
	}
	ft.rows = rows
	return nil
}

// buildPatchMetadataTransform builds the metadata transform ("#P0"): the patch
// Media row, the Patch rows, and the PatchPackage row, diffed against the base.
func (p *msiPatch) buildPatchMetadataTransform() ([]msiStream, error) {
	w := workDBFromDatabase(p.baseDB)

	// Patch Media row: the embedded patch cabinet with its Source property.
	media := w.ensureTable(msiMediaTableName, createMSIMediaTable)
	media.rows = append(media.rows, []any{
		p.patchDiskID,             // DiskId
		p.maxPatchSequence(),      // LastSequence
		nil,                       // DiskPrompt
		"#" + msiPatchCabinetName, // Cabinet (embedded stream)
		nil,                       // VolumeLabel
		msiPatchSourceProperty,    // Source (patch-only)
	})

	// Patch rows: one per staged file, in sequence order.
	patch := w.ensureTable("Patch", createMSIPatchTable)
	for _, c := range p.changes {
		patch.rows = append(patch.rows, []any{
			c.fileID,           // File_
			c.sequence,         // Sequence
			int32(len(c.data)), // PatchSize
			int16(0),           // Attributes
			nil,                // Header
			nil,                // StreamRef_
		})
	}

	// PatchPackage row: registers the patch GUID against the patch media.
	pp := w.ensureTable("PatchPackage", createMSIPatchPackageTable)
	pp.rows = append(pp.rows, []any{p.patchCode, p.patchDiskID})

	target, err := w.materialize()
	if err != nil {
		return nil, err
	}
	summary := (&msiTransform{base: p.base, target: p.upgraded, validation: TransformValidateProduct, errorConditions: patchTransformErrorSuppress}).summaryInfo()
	return buildPatchTransformStreams(p.baseDB, target, summary)
}

// maxPatchSequence returns the highest sequence assigned to a staged file.
func (p *msiPatch) maxPatchSequence() int16 {
	var m int16
	for _, c := range p.changes {
		if c.sequence > m {
			m = c.sequence
		}
	}
	return m
}

// fileRowsByID maps File primary key -> full padded row values for a database.
func fileRowsByID(db msiDatabase) map[string][]any {
	out := map[string][]any{}
	tbl, err := db.GetTable(msiFileTableName)
	if err != nil {
		return out
	}
	cols := tbl.columns()
	for _, r := range tbl.rows() {
		vals := padCells(r.values(), len(cols))
		if id, ok := vals[0].(string); ok {
			out[id] = vals
		}
	}
	return out
}

// orInt16 returns v|bit, treating a nil/absent cell as 0.
func orInt16(v any, bit int16) int16 {
	if x, ok := v.(int16); ok {
		return x | bit
	}
	return bit
}

// msidbFileAttributesPatchAdded marks a File row added by a patch.
const msidbFileAttributesPatchAdded int16 = 0x1000
